version: '3.8'

services:
  web:
    mem_limit: 3g
    cpus: 1.5
    build: .
    command: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b "0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8080:8000"
      #Maps host system's 8080 port to container's 8000 port
    volumes: 
      - .:/app
      # Sync our host with docker for hot reloading
    depends_on:
      - db

  db:
    mem_limit: 3g
    cpus: 1.5
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: EngLab3
    ports:
      - "5432:5432"